### ISSUE TITLE
Moon habitation

### ISSUE THREAD

**Issue by KennethGF** [BotF2/BotF2#200]
Sometimes get too much extra population, like 1,000 or 2,000 instead of 10s more.

**Comment by KennethGF** [comment]
Testing Moon_Habitation in TechObjectDatabase at 25 down from 75. If you get five moons and of large size then the increase could be dramatic.

**Comment by KennethGF** [comment]
Rest the Moon_Habitation in TechObjectDatabase to 5 from 75. Had been increase by someone trying to get extreme populations for the Borg.

**Comment by KennethGF** [comment]
From Gino "The Moon Habitation was at 100% in the queue but I couldn't get it to disappear, after a turn or two. Think we already had this one a while ago. No crash but the colony continues to grow until the Moon Habitation is complete, but with the data on the wrong side. As of now, it only happens for Sol. The other systems work fine."
Suspect this issue is happening in Colony.cs (SupremacyCore\Univser) and something bugging with the property MaxPopulation. See the get code touching on MoonSize, Buildings....) Could there be some funny data for Sol moons?

**Comment by HappyGino** [comment]
I saw what you found, a large section relating to Spied colonies in Colony.cs, (greyed out items, about food, health, morale, population,… (108 to 121)) Does it mean they are unused? (170 to 180 ADD orSUB)
Different things like food reserves, Net food (line 797) production (1013 to 1030) then Food again, Intellingence and Research, Morale then The Net Items (line 1255 to 1268) and lower with the if, case, return, and lower (1717) Credits, Net Energy, NetIntelligence, NetResearch,… Could this have something to do with Spying?
I might be totally out of it though…Then I’m sorry for bothering.

I was just looking for The MoonSize relating to Population when I found it.

Gino

Bonne journée! Have a nice day!

De : Kenneth Of Borg<mailto:notifications@github.com>
Envoyé le :8 janvier 2020 07:05
À : BotF2/BotF2<mailto:BotF2@noreply.github.com>
Cc : Subscribed<mailto:subscribed@noreply.github.com>
Objet :Re: [BotF2/BotF2] Moon habitation (#200)


From Gino "The Moon Habitation was at 100% in the queue but I couldn't get it to disappear, after a turn or two. Think we already had this one a while ago. No crash but the colony continues to grow until the Moon Habitation is complete, but with the data on the wrong side. As of now, it only happens for Sol. The other systems work fine."
Suspect this issue is happening in Colony.cs (SupremacyCore\Univser) and something bugging with the property MaxPopulation. See the get code touching on MoonSize, Buildings....) Could there be some funny data for Sol moons?

**Comment by KennethGF** [comment]
If you open Colony.cs and take the Find in File button (Ctrl+Shift+F) type
in moon and search. That will take you to the MasPopultation property (with
a get) and to the AddBuilding method and RemoveBuilding method that both
take a building parameter.

The other stuff is spy related code. Not clear the current issue is related
to spy as the max population issue was seen before spy started.

ken
